apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prometheus-redirect
  namespace: monitoring
spec:
  parentRefs:
    - kind: Gateway
      name: prod-gw-prometheus
  hostnames:
    - promteheus.prod.cilium.virtualelephant.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            port: 443
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana-redirect
  namespace: monitoring
spec:
  parentRefs:
    - kind: Gateway
      name: prod-gw-grafana
  hostnames:
    - grafana.prod.cilium.virtualelephant.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            port: 443